#!/bin/bash -e

CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

#----------------------------------------------------#
# COMMON ATTRIBUTES                                  #
#----------------------------------------------------#

source $CPWD/scripts/iot-utils

#----------------------------------------------------#
# DEFINES / MACROS                                   #
#----------------------------------------------------#

LOG=$MASTER_DB/iot-domain-default-set.log

#----------------------------------------------------#
# CMDLINE OPTIONS                                    #
#----------------------------------------------------#

ARGC=$#
ARGV=("$@")

VERBOSE=false
HELP=false

# Clear args
set --

COUNT=0
while [ $COUNT -lt $ARGC ]; do
	STRIP=${ARGV[COUNT]}

	ID=0
	LONGFORMAT=`echo $STRIP | cut -b 1-2`
	if [ "x$LONGFORMAT" == "x--" ]; then
		STRIP=`echo ${ARGV[COUNT]} | cut -b 2-3`
	else
		ID=`echo $STRIP | cut -b 3-`
		STRIP=`echo $STRIP | cut -b 1-2`
	fi
	

	if [ "x$STRIP" == "x-v" ]; then
		VERBOSE=true
	elif [ "x$STRIP" == "x-h" ]; then
		HELP=true
	else
		pl
		pr "Error: Unknown argument"
		COUNT=$ARGC
		HELP=true
	fi
COUNT=$((COUNT+1))
done

log "Started"

pl
pg "iot-domain-default-set ($VERSION)"

if [ "$HELP" == "true" ]; then
        pl
	pn "Usage:"
	pl
        pn "Set the default domain used by tools such as"
	pn "iot-cloud-sync and others"
        pl
	pn "iot-domain-default-set [-v] [-h] ..."
	pl
	pn "Help:"
	pl
	pn "-v (--verbose)     Verbose output for operations"
	pn "-h (--help)        Print this"
	pl
	exit 1
fi

#----------------------------------------------------#
# PREPARE                                            #
#----------------------------------------------------#

pn
pg ":: Setup & Checks ::"
pn

common_setup

log "Common Setup OK"

#----------------------------------------------------#
# BODY                                               #
#----------------------------------------------------#

pl
pg ":: Set Default Domain ::"
pl

pn "A domain consists of a Customer ID and a Site ID. Setting"
pn "a default domain provides a safe way for operations to only"
pn "affect the intended domain."
pl

select_domain

pl
pg ":: Final Confirmation ::"
pl

pn "Set the following Customer ID and Site ID as the default domain:"

pl
pnn "Customer ID : "
pg $CUST
pnn "Site ID : "
pg $SITE
pl
pnn "Type 'ok' and Enter to continue : "
read SELECT

if [ "x$SELECT" != "xok" ]; then
	err "User aborted."
fi

log "Default domain set to Customer ID: $CUST, Site ID: $SITE"

pl
pg ":: Performing Actions ::"
pl

pnn "- Setting default domain : "
sed -i '/IOT_DOMAIN/d' $TOOL_SETTINGS
echo "IOT_DOMAIN=$CUST/$SITE" >> $TOOL_SETTINGS
pg "Done"

pl
