#!/bin/bash -e

CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

#----------------------------------------------------#
# COMMON ATTRIBUTES                                  #
#----------------------------------------------------#

source $CPWD/common/iot-utils

#----------------------------------------------------#
# DEFINES / MACROS                                   #
#----------------------------------------------------#

LOG=$MASTER_DB/iot-domain-cloud-update-settings.log

#----------------------------------------------------#
# CMDLINE OPTIONS                                    #
#----------------------------------------------------#

ARGC=$#
ARGV=("$@")

VERBOSE=false
HELP=false

# Clear args
set --

COUNT=0
while [ $COUNT -lt $ARGC ]; do
	STRIP=${ARGV[COUNT]}

	ID=0
	LONGFORMAT=`echo $STRIP | cut -b 1-2`
	if [ "x$LONGFORMAT" == "x--" ]; then
		STRIP=`echo ${ARGV[COUNT]} | cut -b 2-3`
	else
		ID=`echo $STRIP | cut -b 3-`
		STRIP=`echo $STRIP | cut -b 1-2`
	fi
	

	if [ "x$STRIP" == "x-v" ]; then
		VERBOSE=true
	elif [ "x$STRIP" == "x-h" ]; then
		HELP=true
	else
		pl
		pr "Error: Unknown argument"
		COUNT=$ARGC
		HELP=true
	fi
COUNT=$((COUNT+1))
done

log "Started"

pl
pg "iot-domain-cloud-update-settings ($VERSION)"

if [ "$HELP" == "true" ]; then
        pl
	pn "Usage:"
	pl
        pn "Upload the domain settings to the cloud."
        pl
	pn "iot-domain-cloud-update-settings [-v] [-h] ..."
	pl
	pn "Help:"
	pl
	pn "-v (--verbose)     Verbose output for operations"
	pn "-h (--help)        Print this"
	pl
	exit 1
fi

#----------------------------------------------------#
# PREPARE                                            #
#----------------------------------------------------#

pn
pg ":: Setup & Checks ::"
pn

common_setup

log "Common Setup OK"

pnn "- Admin mode enabled : "
ADMIN=$(admin)
if [ "x$ADMIN" == "x1" ]; then
	pg "Yes"
else
	pg "No"
fi

#----------------------------------------------------#
# BODY                                               #
#----------------------------------------------------#

pl
pg ":: Upload Domain Settings ::"
pl

DOMAIN=$(domain)
if [ -z "$DOMAIN" ]; then
	pl
	pr "Error: No default domain is set. Please set it first"
	pl
	exit 1
fi
if [ ! -d $MASTER_DB/$DOMAIN ]; then
	pl
	pr "Error: Domain does not exist. Please create it first."
	pl
	exit 1
fi

CUST=$(dirname $DOMAIN)
SITE=$(basename $DOMAIN)

pl
pnn "Processing settings for Customer ID/Site ID : "
pg $CUST/$SITE

pnn "Netplan config verify : "
netplan_verify $CUST $SITE
pg "Done"

pl
