#!/bin/bash -e

CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

#----------------------------------------------------#
# COMMON ATTRIBUTES                                  #
#----------------------------------------------------#

source $CPWD/common/iot-utils

#----------------------------------------------------#
# DEFINES / MACROS                                   #
#----------------------------------------------------#

LOG=$MASTER_DB/iot-domain-cloud-update-settings.log

#----------------------------------------------------#
# CMDLINE OPTIONS                                    #
#----------------------------------------------------#

ARGC=$#
ARGV=("$@")

VERBOSE=false
HELP=false

# Clear args
set --

COUNT=0
while [ $COUNT -lt $ARGC ]; do
	STRIP=${ARGV[COUNT]}

	ID=0
	LONGFORMAT=`echo $STRIP | cut -b 1-2`
	if [ "x$LONGFORMAT" == "x--" ]; then
		STRIP=`echo ${ARGV[COUNT]} | cut -b 2-3`
	else
		ID=`echo $STRIP | cut -b 3-`
		STRIP=`echo $STRIP | cut -b 1-2`
	fi
	

	if [ "x$STRIP" == "x-v" ]; then
		VERBOSE=true
	elif [ "x$STRIP" == "x-h" ]; then
		HELP=true
	else
		pl
		pr "Error: Unknown argument"
		COUNT=$ARGC
		HELP=true
	fi
COUNT=$((COUNT+1))
done

log "Started"

pl
pg "iot-domain-cloud-update-settings ($VERSION)"

if [ "$HELP" == "true" ]; then
        pl
	pn "Usage:"
	pl
        pn "Upload the domain settings to the cloud."
        pl
	pn "iot-domain-cloud-update-settings [-v] [-h] ..."
	pl
	pn "Help:"
	pl
	pn "-v (--verbose)     Verbose output for operations"
	pn "-h (--help)        Print this"
	pl
	exit 1
fi

#----------------------------------------------------#
# PREPARE                                            #
#----------------------------------------------------#

pn
pg ":: Setup & Checks ::"
pn

common_setup

log "Common Setup OK"

pnn "- Admin mode enabled : "
ADMIN=$(admin)
if [ "x$ADMIN" == "x1" ]; then
	pg "Yes"
else
	pg "No"
fi

#----------------------------------------------------#
# BODY                                               #
#----------------------------------------------------#

pl
pg ":: Domain Selection ::"
pl

DOMAIN=$(domain)

if [ -z "$DOMAIN" ] || [ ! -d $MASTER_DB/$DOMAIN ]; then

	if [ "x$ADMIN" == "x1" ]; then

		CUST_WILDCARD="*** All Customers IDs and Site IDs (dangerous) ***"
		select_domain_cust "$CUST_WILDCARD"
		pl

		if [ ! -z "$CUST" ]; then
			SITE_WILDCARD="*** All Site IDs for selected Customer ID (dangerous) ***"
			select_domain_site "$SITE_WILDCARD"
			pl
		else
			SITE=
		fi

		domain_iterate
	else
		pl
		pr "No default domain is set. Without Admin mode we cannot proceed."
		pl
		exit 1
	fi
else
	# Single Default domain (Non-admin mode compatible)
	DOMAINS=($DOMAIN)
	pn "Default domain selected : $DOMAIN"
	pl
fi


pg ":: Domain Settings Verification ::"
pl


DOMAINS_MAX=${#DOMAINS[@]}
DOMAINS_COUNT=0

while [ $DOMAINS_COUNT -lt $DOMAINS_MAX ] ; do

	DOMAIN_NEXT=${DOMAINS[$DOMAINS_COUNT]}

	CUST=$(dirname $DOMAIN_NEXT)
	SITE=$(basename $DOMAIN_NEXT)
	
	pnn "Domain : "
	pg $CUST/$SITE

	pnn "- Settings location valid : "
	if [ -d $MASTER_DB/$DOMAIN_NEXT/settings ]; then
		pg "Yes"
	else
		pr "No"
		pl
		pr "Error: Settings folder does not exist"
		exit 1
	fi
	
	pnn "- Netplan verification : "
	netplan_verify $CUST $SITE
	pg "Done"

	DOMAINS_COUNT=$((DOMAINS_COUNT + 1))
done

pl
pg ":: Domain Settings Cloud Update ::"
pl

DOMAINS_COUNT=0

while [ $DOMAINS_COUNT -lt $DOMAINS_MAX ] ; do

	DOMAIN_NEXT=${DOMAINS[$DOMAINS_COUNT]}

	CUST=$(dirname $DOMAIN_NEXT)
	SITE=$(basename $DOMAIN_NEXT)

	pnn "Domain : "
	pg $CUST/$SITE

	pnn "- Publishing Domain Settings : "
	update_settings_check
	pg "Done"

	pnn "- Change Status : "
	pg "$SETTINGS_UPDATE_STATUS"
	
	DOMAINS_COUNT=$((DOMAINS_COUNT + 1))

done

pl
