#!/bin/bash -e

CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

#----------------------------------------------------#
# COMMON ATTRIBUTES                                  #
#----------------------------------------------------#

source $CPWD/scripts/iot-utils

#----------------------------------------------------#
# DEFINES / MACROS                                   #
#----------------------------------------------------#

LOG=$LOGS_DIR/iot-firmware-build.log

#----------------------------------------------------#
# CMDLINE OPTIONS                                    #
#----------------------------------------------------#

ARGC=$#
ARGV=("$@")

VERBOSE=false
HELP=false
DEBUG_SHELL=false
PRODUCTION=false


# Clear args
set --

COUNT=0
while [ $COUNT -lt $ARGC ]; do
	STRIP=${ARGV[COUNT]}

	ID=0
	LONGFORMAT=`echo $STRIP | cut -b 1-2`
	if [ "x$LONGFORMAT" == "x--" ]; then
		STRIP=`echo ${ARGV[COUNT]} | cut -b 2-3`
	else
		ID=`echo $STRIP | cut -b 3-`
		STRIP=`echo $STRIP | cut -b 1-2`
	fi
	

	if [ "x$STRIP" == "x-v" ]; then
		VERBOSE=true
	elif [ "x$STRIP" == "x-h" ]; then
		HELP=true
	elif [ "x$STRIP" == "x-d" ]; then
		DEBUG_SHELL=true
	elif [ "x$STRIP" == "x-p" ]; then
		PRODUCTION=true
	else
		pl
		pr "Error: Unknown argument"
		COUNT=$ARGC
		HELP=true
	fi
COUNT=$((COUNT+1))
done

log "Started"

pl
pg "iot-firmware-build ($VERSION)"

if [ "$HELP" == "true" ]; then
	pn "Usage:"
	pl
	pn "Build a device specific firmware image."
	pl
	pn "iot-firmware-build [-v] [-h] ..."
	pl
	pn "Help:"
	pl
	pn "-v (--verbose)      Verbose output for operations"
	pn "-h (--help)         Print this"
	pn "-d (--debug-shell)  Interactive shell"
	pn "-p (--production)   Exclude various debug features from the image"
	pl
	exitbuild
fi

#----------------------------------------------------#
# PREPARE                                            #
#----------------------------------------------------#

pn
pg ":: Setup & Checks ::"
pn

common_setup

log "Common Setup OK"

pnn "- Admin mode enabled : "
ADMIN=$(admin)
if [ "x$ADMIN" == "x1" ]; then
	pg "Yes"
else
	pg "No"
fi

#----------------------------------------------------#
# BODY                                               #
#----------------------------------------------------#

pl
pg ":: Device Selection ::"
pl

DEVICE=$(device)

if [ -z "$DEVICE" ] || [ ! -d $IOT_DEVICE_DIR/$DEVICE ]; then

	if [ "x$ADMIN" == "x1" ]; then

		select_device
	else
		err "No default device is set. Without Admin mode we cannot proceed."
	fi
else
	# Default device (Non-admin mode compatible)
	pnn "- Device selected : "
	pg "$DEVICE"
fi

pl
pg ":: Building Image ::"
pl

if [ ! -f $IOT_DEVICE_DIR/$DEVICE/device-firmware ]; then
	err "Error: Cannot locate firmware script for device: $DEVICE"
fi

source $IOT_DEVICE_DIR/$DEVICE/device-firmware

device_firmware

pl
pnn "Device Firmware Ready : "
pg "$(basename $FIRMWARE_NAME_FINAL)"
pl

