#!/bin/bash -e

CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

#----------------------------------------------------#
# COMMON ATTRIBUTES                                  #
#----------------------------------------------------#

source $CPWD/scripts/iot-utils

#----------------------------------------------------#
# DEFINES / MACROS                                   #
#----------------------------------------------------#

LOG=$LOGS_DIR/iot-firmware-debug.log

#----------------------------------------------------#
# CMDLINE OPTIONS                                    #
#----------------------------------------------------#

ARGC=$#
ARGV=("$@")

VERBOSE=false
HELP=false
DEBUG_SHELL=false
IP=

# Clear args
set --

COUNT=0
while [ $COUNT -lt $ARGC ]; do
	STRIP=${ARGV[COUNT]}

	ID=0
	LONGFORMAT=`echo $STRIP | cut -b 1-2`
	if [ "x$LONGFORMAT" == "x--" ]; then
		STRIP=`echo ${ARGV[COUNT]} | cut -b 2-3`
	else
		ID=`echo $STRIP | cut -b 3-`
		STRIP=`echo $STRIP | cut -b 1-2`
	fi
	

	if [ "x$STRIP" == "x-v" ]; then
		VERBOSE=true
	elif [ "x$STRIP" == "x-i" ]; then
		COUNT=$((COUNT+1))
		IP=${ARGV[COUNT]}
		if [ "x$IP" == "x" ]; then			
			pl
			pr "Error: Unknown argument"
			COUNT=$ARGC
			HELP=true
		fi
	elif [ "x$STRIP" == "x-h" ]; then
		HELP=true
	elif [ "x$STRIP" == "x-d" ]; then
		DEBUG_SHELL=true
	else
		pl
		pr "Error: Unknown argument"
		COUNT=$ARGC
		HELP=true
	fi
COUNT=$((COUNT+1))
done

log "Started"

pl
pg "iot-firmware-debug ($VERSION)"

if [ "$HELP" == "true" ]; then
	pn "Usage:"
	pl
	pn "Debug payload on domain specific device."
	pl
	pn "iot-firmware-debug [-v] [-h] ..."
	pl
	pn "Help:"
	pl
	pn "-v (--verbose)      Verbose output for operations"
	pn "-i (--ip)           Manually supply endpoint IP"
	pn "-h (--help)         Print this"
	pn "-d (--debug-shell)  Interactive shell"
	pl
	exit 0
fi

#----------------------------------------------------#
# PREPARE                                            #
#----------------------------------------------------#

pn
pg ":: Setup & Checks ::"
pn

common_setup

log "Common Setup OK"

#----------------------------------------------------#
# BODY                                               #
#----------------------------------------------------#

pl
pg ":: Device Selection ::"
pl

DEVICE=$(device)

if [ -z "$DEVICE" ] || [ ! -d $IOT_DEVICE_DIR/$DEVICE ]; then

	if [ "x$ADMIN" == "x1" ]; then

		select_device
	else
		err "No default device is set. Without Admin mode we cannot proceed."
	fi
else
	# Default device (Non-admin mode compatible)
	pnn "- Device selected : "
	pg "$DEVICE"
fi


pl
pg ":: Domain Selection ::"
pl

DOMAIN=$(domain)

if [ -z "$DOMAIN" ] || [ ! -d $MASTER_DB/$DOMAIN ]; then

	if [ "x$ADMIN" == "x1" ]; then

		select_domain
	else
		err "No default domain is set. Without Admin mode we cannot proceed."
	fi
else
	# Single Default domain (Non-admin mode compatible)

        CUST=$(dirname $DOMAIN)
        SITE=$(basename $DOMAIN)
fi

pnn "- Domain selected : "
pg "$CUST/$SITE"

pl
pg ":: Endpoint Selection ::"
pl

ENDPOINT=$(endpoint)

if [ -z "$ENDPOINT" ]; then

	if [ "x$ADMIN" == "x1" ]; then

		select_endpoint
	else
		err "No default endpoint is set. Without Admin mode we cannot proceed."
	fi
fi

pnn "- Endpoint selected : "
if [ ! -z "$IP" ]; then
	pg "Manual IP"
else
	pg "$ENDPOINT"
fi

pl
pg ":: Debug Prepare ::"
pl

if [ ! -z "$IP" ]; then
	pnn "- Manual Endpoint IP : "
	ENDPOINT_IP=$IP
	pg "$ENDPOINT_IP"
else
	pnn "- Last Endpoint IP : "
	get_endpoint_ip
	pg "$ENDPOINT_IP"
fi

pnn "- Endpoint Ping : "
run ping -c1 $ENDPOINT_IP
return_check "Failed to ping endpoint IP $ENDPOINT_IP"
pg "OK"
