#!/bin/bash

### DEFINES ###

USER=`whoami`
CPWD="$( cd "$(dirname "$0")" ; pwd -P )"

P_RESET="\e[0m"
P_RED="\e[31m"
P_YELLOW="\e[33m"

### MACROS ###

run() {
        if $VERBOSE; then
                v=$(exec 2>&1 && set -x && set -- "$@")
                echo "#${v#*--}"
                "$@"
        else
                "$@" >/dev/null 2>&1
        fi
}

function pl() {
	echo -e "$P_RESET"
}

function pn() {
	echo -e "$P_RESET$@"
}

function pr() {
	echo -e "$P_RED$@$P_RESET"
}

function py() {
	echo -e "$P_YELLOW$@$P_RESET"
}

function pnn() {
	echo -ne "$P_RESET$@"
}

function prn() {
	echo -ne "$P_RED$@$P_RESET"
}

function pyn() {
	echo -ne "$P_YELLOW$@$P_RESET"
}

CONFIG_USR=/boot/firmware/usercfg.txt
CONFIG_SYS=/boot/firmware/syscfg.txt
CONFIG_CMD=/boot/firmware/cmdline.txt

py "Running Natively"
pl

source $CPWD/device-input

if [ "x$PRODUCTION" == "xtrue" ]; then
        pnn "- Image type : "
	py "Production"
	
	# System Cfg
	echo "### RPI3B ###" > $CONFIG_SYS
	echo "enable_uart=0" >> $CONFIG_SYS

	# User Cfg
	echo "### RPI3B ###" > $CONFIG_USR
	echo "" >> $CONFIG_USR
	echo "dtoverlay=disable-bt" >> $CONFIG_USR
	run systemctl disable hciuart.service
	run systemctl disable bluealsa.service
	run systemctl disable bluetooth.service

	pnn "- Disabling Bluetooth : "
	py "Done"
	pnn "- Disabling UARTs : "
	py "Done"
	pnn "- Disabling SSHD : "
	py "Done"
else
	pnn "- Image type : "
	py "Development"
	
	# System Cfg
	echo "### RPI3B ###" > $CONFIG_SYS
	echo "enable_uart=1" >> $CONFIG_SYS

	# User Cfg
	echo "### RPI3B ###" > $CONFIG_USR
	echo "" >> $CONFIG_USR 
	echo "dtoverlay=disable-bt" >> $CONFIG_USR
	run systemctl disable hciuart.service
	run systemctl disable bluealsa.service
	run systemctl disable bluetooth.service
	
	pnn "- Disabling Bluetooth : "
	py "Done"
	pnn "- Enabling UARTs : "
	py "Done"
	pnn "- Enabling SSHD : "
	touch /boot/firmware/ssh
	py "Done"
fi

pnn "- Writing firmware manifest : "
echo "$VERSION" > $CPWD/.firmware-version
echo "$PRODUCTION" > $CPWD/.firmware-production
echo "$DATE" > $CPWD/.firmware-date
py "Done"

pnn "- Enable Fsck on every boot : "
echo "$(cat $CONFIG_CMD) fsck.mode=force fsck.repair=yes" > $CONFIG_CMD
py "Done"

pnn "- Override flash-kernel for chroot : "
echo "Raspberry Pi 3 Model B Plus Rev 1.3" > /etc/flash-kernel/machine
py "Done"

pnn "- Disable Auto Resize on boot : "
run rm -rf /etc/init.d/resize2fs_once
py "Done"

pnn "- Changing Locale : "
export LANG="en_US.UTF-8"
export LANGUAGE="en_US:en"
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
run locale-gen
run dpkg-reconfigure -f noninteractive locales
py "Done"

pnn "- Install cloud-init user config : "
run cp -f $CPWD/device-files/user-data /boot/firmware
py "Done"

pnn "- Disable Apt cache : "
mkdir -p /etc/apt/apt.conf.d
cp $CPWD/device-files/99noaptcache /etc/apt/apt.conf.d/
rm -rf /var/cache/apt/archives
py "Done"

pnn "- Update System : "
run apt -y remove needrestart
run apt-get update
run apt-get -y dist-upgrade
run apt remove -y unattended-upgrades
py "Done"

pnn "- Installing components : "
run apt-get install -y build-essential vim nano cryptsetup python3-distutils iw wget fake-hwclock ntpdate libraspberrypi-bin wireless-tools
run apt-get install -y python3-pip
run python3 -m pip install --upgrade pip
run python3 -m pip install s3cmd
py "Done"

pnn "- Creating /tmp : "
run mkdir -p /tmp
py "Done"

pnn "- Disable Snapd : "
run apt-get purge -y snapd
py "Done"

pnn "- Compiling and installing xkey : "
run gcc $CPWD/device-files/xkey.c -o $CPWD/device-files/xkey
run chmod +x $CPWD/device-files/xkey
run cp $CPWD/device-files/xkey /bin
py "Done"

pnn "- Installing encrypted drive service : "
run cp $CPWD/device-files/player-hw-test /bin/
run cp $CPWD/device-files/crypt-commission-start /bin/
run cp $CPWD/device-files/crypt-commission-end /bin/
run cp $CPWD/device-files/check-update /bin/
run cp $CPWD/device-files/led-control /bin/
run cp $CPWD/device-files/online-update /bin/
run cp $CPWD/device-files/online-version /bin/
run cp $CPWD/device-files/offline-version /bin/
run cp $CPWD/device-files/*.service /etc/systemd/system
run systemctl enable cryptkey
run systemctl enable payload
run systemctl enable check-update
run systemctl enable ep-update
run systemctl enable hw-update
py "Done"

pnn "- Disable WPA Supplicant Service : "
run systemctl disable wpa_supplicant.service
py "Done"

pnn "- Systemd Network Online Wait Dropin Mod : "
mkdir -p /etc/systemd/system/systemd-networkd-wait-online.service.d/
echo "[Service]" > /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
echo "ExecStart=" >> /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
echo "ExecStart=/lib/systemd/systemd-networkd-wait-online --any" >> /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
py "Done"

pnn "- Refresh shared libraries : "
run ldconfig
py "Done"

if [ "x$DEBUG_SHELL" == "xtrue" ]; then
	pl
	py "Interactive terminal (type 'exit' to finish) : "
	pl
	bash
	pl
fi

pnn "- Remove flash-kernel override for chroot : "
run rm -rf /etc/flash-kernel/machine
py "Done"
