#!/bin/bash

ONLINE=0

wget -q --spider http://google.com
RET=$?
if [ $RET -eq 0 ]; then
	ONLINE=1
fi
	
cat /home/iot/payload/.version > /run/.payload-version 

if [ $ONLINE -eq 1 ] && [ -f /run/commission/.s3cfg-download ] && [ -f /run/commission/.cust ] && [ -f /run/commission/.site ]; then
	s3cmd -q -f --config /run/commission/.s3cfg-download get --no-preserve s3://iot-device-download/$(cat /run/commission/.cust)/$(cat /run/commission/.site)/payload/.version /run/.payload-version
fi

cat /run/.payload-version
