#!/bin/bash

BOOT_DIR=/boot/firmware/eplayer
ENC_NAME=enc_drive
ENC_PATH=/home/eplayer/$ENC_NAME

echo "Crypt-Commission: Umount"
/usr/bin/sync
/usr/bin/umount $ENC_PATH

echo "Crypt-Commission: Closing Drive"
/usr/sbin/cryptsetup luksClose $ENC_NAME
